apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-simple
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-simple
  template:
    metadata:
      labels:
        app: node-simple
    spec:
      containers:
      - name: node-app
        image: shravan256bit/nodeimage:v1 
        ports:
        - containerPort: 3000

