replicaCount: 3

image:
  repository: shravan256bit/nodeimage
  tag: latest

service:
  type: NodePort
  port: 80          # Service 
  targetPort: 3000  # Container port
  nodePort: 30011   # NodePort

